version: '3'
 
services:
  db:
    image: mysql:8.0
    container_name: db
    command: --init-file /app/init.sql
    volumes:
        - ./init.sql:/app/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: splitwise
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      # PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  splitwise:
    build: .
    container_name: splitwise
    links:
      - db
    ports:
      - 5000:5000
